### ISSUE TITLE
Connection to IBM i keeps disconnecting. Error in dev tools console.

### ISSUE THREAD

**Issue by KerimG** [codefori/vscode-ibmi#2069]
After successfully connecting to the IBM i, I get a pop-up saying "Connection lost" with the following error in the console. Not sure if the error is related, though. 

```
mainThreadExtensionService.ts:82 Error: No such file
	at 101 (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:232673)
	at SFTP.push (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:249360)
	at CHANNEL_DATA (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:167608)
	at 94 (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:332785)
	at e.exports.U (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:193609)
	at F.decrypt (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:289945)
	at e.exports.$ [as _parse] (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:193133)
	at e.exports.parse (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:197520)
	at Socket.<anonymous> (c:\Users\VRPG\.vscode\extensions\halcyontechltd.code-for-ibmi-2.10.1\dist\extension.js:2:169786)
	at Socket.emit (node:events:517:28)
	at addChunk (node:internal/streams/readable:335:12)
	at readableAddChunk (node:internal/streams/readable:308:9)
	at Readable.push (node:internal/streams/readable:245:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Expected behavior**
I expected the connection to maintain.

**Screenshots**
![image](https://github.com/codefori/vscode-ibmi/assets/9061713/ce27348e-590c-4462-bfbc-b11d3ca6b389)

**Environment (please complete the following information):**
 - Extension version 2.10.1
 - IBM i OS version 7.4

**Additional context**
~~When connecting via SSH in the Windows terminal or git bash, the connection is stable.~~

I just realized that regular SSH connections also drop. This is a foreign IBM i to me and I'm not sure what the problem is. Will investigate. Leaving this up, just in case those issues are actually not related.

Is there a way for me to show more information?

**Comment by chrjorgensen** [comment]
Hi @KerimG 

The SSH client can take additional parameters, including '-vvv' for verbose debug info. 
PuTTY also has a debug setting in the connection. 

HTH.

**Comment by KerimG** [comment]
Hey @chrjorgensen , 

thanks for the info. I forgot to close the ticket. Turns out the sysadmin of the system set the SSH server's `ClientAliveTimeout` to 10 for no reason, because they thought it's more secure that way...
