### ISSUE TITLE
Service Entry Points Not Added To List 

### ISSUE THREAD

**Issue by AARPETERSON** [codefori/vscode-ibmi#2247]
👉🏻 Issue text goes here.

When attempting to create a service entry point, none is created in the extension. Seeing the below in the debug console after attempting to start a SEP. 

![image](https://github.com/user-attachments/assets/5ce0be5f-415e-4c51-8696-91e3adf52326)

From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"IBMiDebug","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsEvaluateForHovers":true,"supportsSetVariable":true,"supportsValueFormattingOptions":true,"supportsModulesRequest":true,"supportTerminateDebuggee":true,"supportsFunctionBreakpoints":true,"supportsConfigurationDoneRequest":true}}
From client: launch({"type":"IBMiDebug","request":"launch","subType":"sep","action":"set","name":"Service Entry Point","user":"APETERSON","host":"SILVERLAKE.JHACORP.COM","port":8005,"sepDaemonPort":8008,"secure":true,"ignoreCertificateErrors":false,"library":"AARONP","program":"RTEFTSEQCK","programType":"*PGM","module":"*ALL","procedure":"*ALL","trace":true,"workbenchSettings":{"updateProductionFiles":false,"enableDebugTracing":true,"connection":{"connectionPort":8001}},"__sessionId":"eb109d50-7881-4382-8d57-6ceb57f5107e"})
To client: {"type":"event","seq":2,"event":"initialized"}
From client: setBreakpoints({"source":{"name":"RTEFTSEQCK.SQLRPGLE","path":"member:/AARONP/QRPGLESRC/RTEFTSEQCK.SQLRPGLE?readonly%3Dfalse%26position%3D"},"lines":[],"breakpoints":[],"sourceModified":false})
From client: setFunctionBreakpoints({"breakpoints":[]})
To client: {"type":"response","seq":0,"request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[]}}
To client: {"type":"response","seq":0,"request_seq":4,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]}}
From client: configurationDone(undefined)
To client: {"type":"response","seq":0,"request_seq":5,"success":true,"command":"configurationDone"}
From client: threads(undefined)
To client: {"type":"response","seq":0,"request_seq":6,"success":true,"command":"threads","body":{"threads":[]}}
To client: {"type":"event","seq":7,"event":"exited","body":{"exitcode":0,"message":"DBGM0007I Created service entry point on AARONP/RTEFTSEQCK *PGM."}}
To client: {"type":"event","seq":8,"event":"terminated"}
To client: {"type":"response","seq":0,"request_seq":2,"success":true,"command":"launch"}
To client: {"type":"response","seq":0,"request_seq":5,"success":false,"command":"configurationDone","body":{"error":{"id":"8999","format":"java.lang.NullPointerException\n\tat com.ibm.debug.pdt.daas.internal.dap.DAPSession.getVersionJSON(DAPSession.java:439)\n\tat com.ibm.debug.pdt.daas.internal.dap.events.DAPEvent.getEvent(DAPEvent.java:117)\n\tat com.ibm.debug.pdt.daas.internal.dap.requests.DAPConfigurationDoneRequest.generateEvents(DAPConfigurationDoneRequest.java:123)\n\tat com.ibm.debug.pdt.daas.internal.dap.requests.DAPRequest.process(DAPRequest.java:139)\n\tat com.ibm.debug.pdt.daas.internal.dap.requests.DAPRequest.process(DAPRequest.java:97)\n\tat com.ibm.debug.pdt.daas.internal.dap.DAPRequestProcessor$1.run(DAPRequestProcessor.java:119)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\n"}}}
From client: disconnect({"restart":false,"terminateDebuggee":false})

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.13.1-dev.0|
|Visual Studio Code version|1.75.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
.NET Install Tool (vscode-dotnet-runtime): 2.1.1
COBOL (cobol): 9.3.2
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.3.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.8.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.11.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.8
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.18
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|9|
|CCSID Origin|65535|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|
|bash|attr|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||
|ls|setccsid|||
|md5sum|tar|||
|sort||||
|stat||||
|tn5250||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=R4DATDD
CURLIB=R4DATDD
HOME=/home/APETERSON
HOST=silverlake.jhacorp.com
LIBLS=AARONP QDEVTOOLS RSUPTOOLS JHAREMOTE SLAKEUTIL JHASYSI R4SRCJHA R4SRCCMJHA R4SRCSUP R4JHACMJHA R4RUNJHA R4RUNCOM R4RUNDD R4DATDD
LOGIN=apeterson
LOGNAME=apeterson
MAIL=/var/spool/mail/apeterson
OLDPWD=/home/APETERSON
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/APETERSON
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1

TZ=<CST>6<CDT>,M3.2.0,M11.1.0
USER=apeterson
USERNAME=apeterson
WORKDIR=/home/APETERSON
_=/QOpenSys/pkgs/bin/env
```
</details>

**Comment by AARPETERSON** [comment]
************Beginning of data**************                                  
Created IBM i connection for SEP (host: LOCALHOST, user: APETERSON)           
Connected to host LOCALHOST                                                   
                                                                              
DBGM0007I Created service entry point on AARONP/RTEFTSEQCK *PGM.              
 ************End of Data********************                                  
 
 
 
 
 !SESSION 2024-09-03 07:57:48.812 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=11.0.21+9
JRE 11 OS/400 ppc64-64-Bit Compressed References 20231213_000000 (JIT enabled, AOT enabled)
OpenJ9   - 461bf3c70
OMR      - 5eee6ad9d
JCL      - 6f4cc08025 based on jdk-11.0.21+9
BootLoader constants: OS=os/400, ARCH=ppc64, WS=unknown, NL=en_US
Framework arguments:  -application com.ibm.etools.iseries.daas.application -localonly -secureport=8005 -port=8001 -sepdaemonport=8008 -keystore=/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx -keystorepassword=O_sYZ/jw7M6orFf4QUX7dDK2cEWt1QO1QZ+6CAqThWPDQiwvmj24eahWeZrktNcr2omnA2mT+IRsySoSpHxcc+pQ
Command-line arguments:  -application com.ibm.etools.iseries.daas.application -data /QIBM/UserData/IBMiDebugService/startDebugService_workspace -localonly -secureport=8005 -port=8001 -sepdaemonport=8008 -keystore=/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx -keystorepassword=O_sYZ/jw7M6orFf4QUX7dDK2cEWt1QO1QZ+6CAqThWPDQiwvmj24eahWeZrktNcr2omnA2mT+IRsySoSpHxcc+pQ

!ENTRY org.eclipse.core.resources 2 10035 2024-09-03 07:57:58.240
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY com.ibm.etools.iseries.debug.core 4 0 2024-09-03 08:23:15.776
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at com.ibm.etools.iseries.daas.internal.dap.ServiceEntryPointDaemon.getKeyStore(ServiceEntryPointDaemon.java:215)
	at com.ibm.etools.iseries.daas.internal.dap.ServiceEntryPointDaemon.getSSLContext(ServiceEntryPointDaemon.java:173)
	at com.ibm.etools.iseries.daas.internal.dap.ServiceEntryPointDaemon.run(ServiceEntryPointDaemon.java:79)

!ENTRY com.ibm.etools.iseries.services.qsys 1 0 2024-09-03 08:23:15.914
!MESSAGE ToolboxConnectorService.internalConnect: connecting LOCALHOST

!ENTRY com.ibm.etools.iseries.services.qsys 1 0 2024-09-03 08:23:15.942
!MESSAGE ToolboxConnectorService.internalConnect(): Login with IBM i UserID and Password

!ENTRY com.ibm.etools.iseries.services.qsys 1 0 2024-09-03 08:23:16.088
!MESSAGE ToolboxConnectorService.internalConnect: connected LOCALHOST

!ENTRY com.ibm.debug.pdt.daas.application 2 0 2024-09-03 08:23:19.041
!MESSAGE unable to configure termination, default termination used

!ENTRY com.ibm.debug.pdt.daas.application 4 0 2024-09-03 08:23:19.077
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at com.ibm.debug.pdt.daas.internal.dap.DAPSession.getVersionJSON(DAPSession.java:439)
	at com.ibm.debug.pdt.daas.internal.dap.events.DAPEvent.getEvent(DAPEvent.java:117)
	at com.ibm.debug.pdt.daas.internal.dap.requests.DAPConfigurationDoneRequest.generateEvents(DAPConfigurationDoneRequest.java:123)
	at com.ibm.debug.pdt.daas.internal.dap.requests.DAPRequest.process(DAPRequest.java:139)
	at com.ibm.debug.pdt.daas.internal.dap.requests.DAPRequest.process(DAPRequest.java:97)
	at com.ibm.debug.pdt.daas.internal.dap.DAPRequestProcessor$1.run(DAPRequestProcessor.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by AARPETERSON** [comment]
Below from /qibm/UserData/IBMIDEBUGSERVICE/./startDebugService_workspace/.metadata/.log  

This is what I am continuing to see when attempting to add service entry points. I will note that the batch debug and attaching to a running job appears to be operational. I just cannot get SEP's working to break into something. 

!ENTRY com.ibm.debug.pdt.daas.application 2 0 2024-10-24 13:07:34.968                                                            !MESSAGE unable to configure termination, default termination used                                                               !ENTRY com.ibm.debug.pdt.daas.application 4 0 2024-10-24 13:07:34.978                                                            !MESSAGE NullPointerException                                                                                                    !STACK 0                                                                                                                         java.lang.NullPointerException                                                                                                   at com.ibm.debug.pdt.daas.internal.dap.DAPSession.getVersionJSON(DAPSession.java:439)                                           at com.ibm.debug.pdt.daas.internal.dap.events.DAPEvent.getEvent(DAPEvent.java:117)                                              at com.ibm.debug.pdt.daas.internal.dap.requests.DAPConfigurationDoneRequest.generateEvents(DAPConfigurationDoneRequest.java:123)at com.ibm.debug.pdt.daas.internal.dap.requests.DAPRequest.process(DAPRequest.java:139)                                         at com.ibm.debug.pdt.daas.internal.dap.requests.DAPRequest.process(DAPRequest.java:97)                                          at com.ibm.debug.pdt.daas.internal.dap.DAPRequestProcessor$1.run(DAPRequestProcessor.java:119)                                  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by AARPETERSON** [comment]
@mkwan01 here you are... 

DEBUG_SERVICE_KEYSTORE_PASSWORD=O_sYZ/jw7M6orFf4QUX7dDK2cEWt1QO1QZ+6CAqThWPDQiwvmj24eahWeZrktNcr2omnA2mT+IRsySoSpHxcc+pQ


.code4i.debug
KEY=DhpFqjAHJlmGieTQSdf1fQ==
PARAMETER_SPEC=CJh9T337m7AA9wCfTRH1zg==

**Comment by mkwan01** [comment]
@AARPETERSON I created a standalone program to test the decryption of the provided DEBUG_SERVICE_KEYSTORE_PASSWORD with the corresponded key file. The program reports that the provided password is invalid:
EBUG_SERVICE_KEYSTORE_PASSWORD=O_sYZ/jw7M6orFf4QUX7dDK2cEWt1QO1QZ+6CAqThWPDQiwvmj24eahWeZrktNcr2omnA2mT+IRsySoSpHxcc+pQ

We need to trace the path on how this invalid password is generated. Before doing this, we need to verify whether this problem still exists in the newer debug client (2.0.2) and the updated debug service PTF (v2.0.1). Please update the debug client to v2.0.2 and install the following host PTFs and try the scenario again:
7.3 PTF SJ02996
7.4 PTF SJ03026
7.5 PTF SJ03030

If the problem is still there, then we will trace the password generation code to look for a possible cause.

**Comment by mkwan01** [comment]
@worksofliam Please add an info-needed label to this one. Thanks.
